include("${CMAKE_CURRENT_LIST_DIR}/vescuartTargets.cmake")

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/Modules")

set(VESCUART_INCLUDE_DIRS
    @VESCUART_INSTALL_INCLUDE_DIRS@
)

set(VESCUART_DEFINITIONS "")
set(VESCUART_LIBRARIES vescuart::vescuart)
set(VESCUART_STATIC_LIBRARIES
    vescuart::vescuart_static
)

find_package(Boost REQUIRED COMPONENTS 
    system
    thread)
list(APPEND VESCUART_INCLUDE_DIRS ${Boost_INCLUDE_DIRS})
list(APPEND VESCUART_DEFINITIONS ${Boost_LIB_DIAGNOSTIC_DEFINITIONS})
list(APPEND VESCUART_LIBRARIES ${Boost_LIBRARIES})

set(VESCUART_FOUND TRUE)
